### ISSUE TITLE
[Roadmap] Consider Java bindings

### ISSUE THREAD

**Issue by binkley** [klogging/klogging#1]
Consider support for Java uptake of this library, if that make sense

**Comment by mjstrasser** [comment]
Java uptake will be on the roadmap. The `NoCoLogger` idea is for logging from non-coroutine code that will support it.

More important is for Kotlin code to use the library in Java frameworks (e.g. Spring Boot) where there is no current coroutine context.

I also plan to investigate an Slf4j adapter.
