### ISSUE TITLE
Base context items are not copied to log events that are sended directly

### ISSUE THREAD

**Issue by strelchm** [klogging/klogging#131]
If we consider two methods in _**io.klogging.internal.Dispatcher**_ then we see that method "send" includes base context items to log event:
```
    /**
     * Dispatch a [LogEvent] to selected targets. Base context items are included here.
     *
     * Each is dispatched in a separate coroutine.
     */
    internal suspend fun send(logEvent: LogEvent) {
        // If we are tracing Klogging, add event ID to the items map.
        val event = logEvent.addContext(traceContext(logEvent) + KloggingEngine.baseContextItems)

        cachedSinksFor(logEvent.logger, logEvent.level)
            .forEach { sink ->
                trace("Dispatcher", "Dispatching event ${event.id} to sink ${sink.name}")
                sink.send(event)
            }
    }
```
but method "sendDirect" constructs logEvent with base context items but then the variable "event" is used only in trace log:
```
    /**
     * Dispatch a [LogEvent] directly to each sink.
     */
    internal suspend fun sendDirect(logEvent: LogEvent) {
        val event = logEvent.addContext(traceContext(logEvent) + KloggingEngine.baseContextItems)
        cachedSinksFor(logEvent.logger, logEvent.level)
            .forEach { sink ->
                trace("Dispatcher", "Dispatching event ${event.id} directly to sink ${sink.name}")
                sink.sendDirect(logEvent)
            }
    }
```
What is preffered way to put MDC variables to logEvent with level >= KloggingEngine.minDirectLogLevel()? No information in docs. And if there is no mistacke in method "sendDirect", why we construct new event with actual contexts and then we don't use it in this method?

**Comment by mjstrasser** [comment]
Hi @strelchm, thanks for looking at Klogging. 

This looks like a bug in the dispatcher. I will check now.

**Comment by mjstrasser** [comment]
I fixed the bug where `Dispatch.sendDirect()` dispatched the wrong event. Thank you for pointing that out. Version 0.4.15 of Klogging has the fix.

But you mentioned MDC, which is not a Klogging concept. MDC is part of Java libraries Log4J, Logback and SLF4J. Context items in Klogging are set using coroutine context functions (e.g. `withContext()`).

To use MDC with Klogging you need to use [slf4j-klogging](https://github.com/klogging/slf4j-klogging). That library [includes MDC entries in the items](https://github.com/klogging/slf4j-klogging/blob/cfab2873b7ec8202de30772a67b312060b6ae989/src/main/kotlin/io/klogging/slf4j/NoCoLoggerWrapper.kt#L190) attached to the log event.

Is that what you need? Can you share some code to show what you are doing and what you expect to see?

**Comment by mjstrasser** [comment]
Version 0.3.4 of both [slf4j-klogging](https://github.com/klogging/slf4j-klogging) and of [klogging-spring-boot-starter](https://github.com/klogging/klogging-spring-boot-starter) has the bugfix included.

**Comment by strelchm** [comment]
> are some code to show what you are doing and what you expect to see?

Yes this fix is what I needed - I mixed meanings of MDC and base context in description. The using is next: 
`            Context.clearBaseContext()
            Context.addBaseContext(...)`
and the fix treats the adding of props to direct sending

Thanks much!

**Comment by mjstrasser** [comment]
Thanks for finding the bug!
