### ISSUE TITLE
Problem when sending logs from a thread with dots in the name

### ISSUE THREAD

**Issue by cwrau** [klogging/klogging#135]
I'm using okhttp via fabric8 as a kubernetes client instrumented via opentelemetry with tracing.

When sending spans and it fails opentelemetry logs something.

With `jul-to-slf4j` and `slf4j-klogging` I managed to get the logs into klogging.

Now, the thread has the name `OkHttp http://localhost:4317/...` and when using the ANSI renderer the `...` makes it crash, specifically the line https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/rendering/RenderAnsi.kt#L68

You split the context, which in my case is the thread name, by `.`, loop over them and without checking the length of the word do a `substring` on the word.

I guess you're assuming the context is always a class name? 🤔
But in https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/impl/NoCoLoggerImpl.kt#L48 you're always using the thread name, so I don't even see a way to fix this on my end 🤷

**Comment by mjstrasser** [comment]
Hi @cwrau, thanks for trying Klogging!

Thanks for raising this issue. I think you have pinpointed the problem correctly. I will look into it now.

**Comment by mjstrasser** [comment]
Ah yes, I see! `RenderAnsi` uses `compressName` function for both logger names (typically fully-qualified class names)
and for contexts (typically thread names).

I have a new build of Klogging with a new `shortenName` function that shortens segments of a name from left to right
until they fit into the space, using a range of delimiters and ignoring consecutive delimiters. Some
examples [from the tests](https://github.com/klogging/klogging/blob/5d42aae831e940ef94364c8dd02a9f06218a9d62/klogging/src/jvmTest/kotlin/io/klogging/rendering/RenderAnsiTest.kt#L26):

| Name                                 | Shortened name (20 chars max) |
|--------------------------------------|-------------------------------|
| `main`                               | `main`                        |
| `io.klogging.events.LogEvent`        | `i.k.events.LogEvent`         |
| `DefaultDispatcher-worker-3+Playpen` | `D-worker-3+Playpen`          |
| `OkHttp http://localhost:4317/...`   | `O h://l:4317/...`            |
| `Triantiwontigongalope`              | `Triantiwontigongalop`        |

That should fix your issue. Do you think those shortenings make enough sense when you read logs?

Version 0.4.18 of Klogging has the fix.

**Comment by cwrau** [comment]
Yeah, that looks great!

But it came to my mind, is it really necessary to shorten these things? 🤔

I mean, I've always seen logs with the shortened stuff, so I'm used to it, but is it technically necessary? 🤔

Logs are for debugging, why not print the whole thing?

Aside from that philosophical question this should work, I'll try it out when I get the time!

**Comment by mjstrasser** [comment]
Glad to know it works for you!

Why shorten names? I copied the idea from one of the Log4j appenders. I see the value, when eyeballing thousands of log messages in a console or text file, of having repetitive information lined up so the interesting stuff starts in the same column. 

This is only relevant for the console and text files. Klogging writes full strings to other sinks like Splunk and Seq.

For example:

<img width="1085" alt="image" src="https://github.com/klogging/klogging/assets/168173/386daedf-ec53-421f-87ad-6d9b5d3a1e1a">

**Comment by mjstrasser** [comment]
@cwrau Are you finding Klogging useful? I am interested to know how you are using it, and features you would like to see implemented.

**Comment by cwrau** [comment]
> Glad to know it works for you!
> 
> Why shorten names? I copied the idea from one of the Log4j appenders. I see the value, when eyeballing thousands of log messages in a console or text file, of having repetitive information lined up so the interesting stuff starts in the same column. 
> 
> This is only relevant for the console and text files. Klogging writes full strings to other sinks like Splunk and Seq.
> 
> For example:
> 
> <img width="1085" alt="image" src="https://github.com/klogging/klogging/assets/168173/386daedf-ec53-421f-87ad-6d9b5d3a1e1a">
> 

Ah, I see, yes, that does make sense!

**Comment by cwrau** [comment]
> @cwrau Are you finding Klogging useful? I am interested to know how you are using it, and features you would like to see implemented.

Most definitely, it's my go to library for logging in kotlin 😁

I've been using it in cli apps, cronjob-like jobs and server applications 👍
Really a good library 👌
Especially the tooling to route the other logging APIs to klogging 👏

And feature wise, I guess the only thing would be environment based configuration without the user having to write code 🤔

Because locally I like the ANSI output but during deployment I like the JSON output

**Comment by mjstrasser** [comment]
> Most definitely, it's my go to library for logging in kotlin 😁
> 
> I've been using it in cli apps, cronjob-like jobs and server applications 👍 Really a good library 👌 Especially the tooling to route the other logging APIs to klogging 👏

Thank you! That is good to know.

> And feature wise, I guess the only thing would be environment based configuration without the user having to write code 🤔

I am not sure what you mean. Do you know that you can specify the path of a JSON or HOCON configuration file in the environment variable `KLOGGING_CONFIG_PATH`? I have used it with paths to different JSON files in different environments.

It is not documented that clearly but is described on the [Environment variables page](https://klogging.io/docs/internals/environment-variables). I will improve that.

**Comment by cwrau** [comment]
> > And feature wise, I guess the only thing would be environment based configuration without the user having to write code 🤔
> 
> I am not sure what you mean. Do you know that you can specify the path of a JSON or HOCON configuration file in the environment variable `KLOGGING_CONFIG_PATH`? I have used it with paths to different JSON files in different environments.
> 
> It is not documented that clearly but is described on the [Environment variables page](https://klogging.io/docs/internals/environment-variables). I will improve that.


Mh, yeah, I missed that 😅 

But if possible it would be awesome if environment variables would enough. 
Otherwise I'd have to write a configmap and mount it into the container inside kubernetes 😅

**Comment by cwrau** [comment]
> Do you need other environment variables? What do you have in mind?

Something like `KLOGGING_OUTPUT_FORMAT` with values like `ANSI`, `CLEF`,... 🤔

**Comment by mjstrasser** [comment]
> Something like `KLOGGING_OUTPUT_FORMAT` with values like `ANSI`, `CLEF`,... 🤔

If I understand what you mean, it is possible already to specify different output formats for each sink, especially to STDOUT.

For example, if you have services logging to stdout and logs are collected and forwarded to a Seq server, you can put this into JSON configuration:

```json
  "sinks": {
    "stdout": {
      "renderWith": "RENDER_CLEF",
      "sendTo": "STDOUT"
    }
  }
```

I do not have a separate renderer for Splunk yet. The current code for creating Splunk HEC records cannot implement the [functional type `RenderString`](https://github.com/klogging/klogging/blob/1a7d760e97c988cc66a7be8ef49c946cb19051c8/klogging/src/commonMain/kotlin/io/klogging/rendering/Render.kt#L24) because it includes information about the Splunk endpoint as well. If you need that, I can figure out a way to make it available.

**Comment by cwrau** [comment]
> > Something like `KLOGGING_OUTPUT_FORMAT` with values like `ANSI`, `CLEF`,... 🤔
> 
> If I understand what you mean, it is possible already to specify different output formats for each sink, especially to STDOUT.
> 
> For example, if you have services logging to stdout and logs are collected and forwarded to a Seq server, you can put this into JSON configuration:
> 
> ```json
>   "sinks": {
>     "stdout": {
>       "renderWith": "RENDER_CLEF",
>       "sendTo": "STDOUT"
>     }
>   }
> ```
> 
> I do not have a separate renderer for Splunk yet. The current code for creating Splunk HEC records cannot implement the [functional type `RenderString`](https://github.com/klogging/klogging/blob/1a7d760e97c988cc66a7be8ef49c946cb19051c8/klogging/src/commonMain/kotlin/io/klogging/rendering/Render.kt#L24) because it includes information about the Splunk endpoint as well. If you need that, I can figure out a way to make it available.
> 

Yeah, of course it's possible with the config file, but my request would be to change the format via a single environment variable 😅

**Comment by mjstrasser** [comment]
@cwrau I have been thinking about your request. 

Configuring Klogging requires:
+ defining one or more sinks, each with destination and format; and
+ defining one or more logging matchers by logger name and level.

You can’t represent all of that in one environment variable.

Here is an idea. First, define a simple configuration in JSON:

```json
{
  "sinks": {
    "stdout": {
      "renderWith": "RENDER_ANSI",
      "sendTo": "STDOUT"
    }
  },
  "logging": [
    {
      "levelRanges": [
        {
          "fromMinLevel": "INFO",
          "toSinks": ["stdout"]
        }
      ]
    }
  ]
}
```

Then, the environment variable `KLOGGING_OUTPUT_FORMAT_STDOUT=CLEF` causes Klogging to use `RENDER_CLEF` instead of `RENDER_ANSI`.

It would work because the variable ends with the name of the sink `stdout` converted to upper case, and the value is the name of a built-in renderer (omitting the `RENDER_` prefix).

What do you think? Is that the kind of thing you have in mind?

**Comment by cwrau** [comment]
> @cwrau I have been thinking about your request. 
> 
> Configuring Klogging requires:
> + defining one or more sinks, each with destination and format; and
> + defining one or more logging matchers by logger name and level.
> 
> You can’t represent all of that in one environment variable.

And I don't need the whole structure to be represented, just the overall output format, for which I'd have two ideas;

1. One would be the same as your idea;

> Here is an idea. First, define a simple configuration in JSON:
> 
> ```json
> {
>   "sinks": {
>     "stdout": {
>       "renderWith": "RENDER_ANSI",
>       "sendTo": "STDOUT"
>     }
>   },
>   "logging": [
>     {
>       "levelRanges": [
>         {
>           "fromMinLevel": "INFO",
>           "toSinks": ["stdout"]
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> Then, the environment variable `KLOGGING_OUTPUT_FORMAT_STDOUT=CLEF` causes Klogging to use `RENDER_CLEF` instead of `RENDER_ANSI`.
> 
> It would work because the variable ends with the name of the sink `stdout` converted to upper case, and the value is the name of a built-in renderer (omitting the `RENDER_` prefix).

Meaning a semi-powerful environment variable parsing feature. 

2. And the other one would be to just have `KLOGGING_OUTPUT_FORMAT=CLEF'. 
Nothing more, nothing complex, just all the sinks rendering with the specified format. 

> What do you think? Is that the kind of thing you have in mind?

I would actually prefer 2. as that's easier to configure and I would argue that you'd want all outputs to have the same format and, following the [12 factors' logging spec](https://12factor.net/logs), output to stdout anyways.
And maybe this would be easier to implement as well.

**Comment by mjstrasser** [comment]
@cwrau An update: I am working on option 1.

The issue with option 2 is that it is incomplete from a Klogging perspective. If you are using Klogging in back-end services they should be 12-factor apps, but I want Klogging to be suitable for a wider range of uses.

I am nearly there; I have a bug to iron out first.

**Comment by mjstrasser** [comment]
Try version 0.4.20 with setting `KLOGGING_OUTPUT_FORMAT_STDOUT` and let me know if it works for you.
