### ISSUE TITLE
Accessing STDERR sender internal?

### ISSUE THREAD

**Issue by stevepentland** [klogging/klogging#140]
### Discussed in https://github.com/klogging/klogging/discussions/139
I had originally made this in discussions but it seems like issues may be a better place so I'm moving it into here. Sorry for the duplicates!

<div type='discussions-op-text'>

<sup>Originally posted by **stevepentland** July 19, 2023</sup>
Hi, I am trying to use the DSL configuration style when setting up logging. However when I try to do the following (from the docs at https://klogging.io/docs/configuration/dsl#a-more-complex-example) I am unable to access STDERR
```
sink("stderr", RENDER_SIMPLE, STDERR)
```
and it appears it is internal in `STDERR.kt`. What am I doing wrong?</div>

**Comment by mjstrasser** [comment]
@stevepentland Thanks for trying out Klogging! And thanks for finding a bug.

You are right: [`STDERR` is `internal` but should be `public`](https://github.com/klogging/klogging/blob/c49202e5c8573740bae900feb470631d3edec0de/klogging/src/commonMain/kotlin/io/klogging/sending/SendConsole.kt#L25). 

I will fix that now.

**Comment by stevepentland** [comment]
Awesome thank you so much!

**Comment by mjstrasser** [comment]
Building release 0.4.19 now.

**Comment by mjstrasser** [comment]
@stevepentland Version 0.4.19 is released. Let me know if you have any issues!
