### ISSUE TITLE
New `KLOGGING_OUTPUT_FORMAT_STDOUT` feature feedback

### ISSUE THREAD

**Issue by cwrau** [klogging/klogging#144]
Try version 0.4.20 with setting `KLOGGING_OUTPUT_FORMAT_STDOUT` and let me know if it works for you.

_Originally posted by @mjstrasser in https://github.com/klogging/klogging/issues/135#issuecomment-1643388559_
            

I finally got to try this out and I got two issues with that. 😅

Firstly, this results in two different log formats being used;

```log
10:40:31.540076647  INFO [                main] :        Configuration : Reading configuration from klogging.json on the classpath
10:41:01.997587367  INFO [                main] :        Configuration : Updating sink stdout format to CLEF
{"@t":"2023-07-27T08:41:06.487570996Z","@l":"INFO","host":"steve","logger":"net.teuto.portal.k8s.worker.WorkerApplicationCommand","context":"main","@m":"Starting up..."}
```

This creates problems when using a log management system like loki which tries to parse the logs.

Also, I'd just expect setting the logging format should immediately take effect and everything should adhere to that.

Additionally, I would like to turn off these two `Configuration` log messages 😅
Or maybe just have them as trace 😅

---

Additionally, the flag only sets the output format for a single sink 😅

I would expect the environment variable to affect all output.
Especially because I don't see the reality in which you'd want different log formats 🤔

**Comment by mjstrasser** [comment]
The issue you have seen is with the output from [Klogging’s internal logger](https://klogging.io/docs/internals/internal-logger). It does not log very often and has a different set of rules. 

You can effectively disable it with `KLOGGING_MIN_LOG_LEVEL=FATAL` in the environment.

I am not convinced that everybody wants what you want but I will think about how it can be accommodated.

**Comment by cwrau** [comment]
> The issue you have seen is with the output from [Klogging’s internal logger](https://klogging.io/docs/internals/internal-logger). It does not log very often and has a different set of rules.
> 
> You can effectively disable it with `KLOGGING_MIN_LOG_LEVEL=FATAL` in the environment.

Ah, nice 👍️

I first thought this would be the global minimum log level, but yes, this does only change it for the internal logger 👌

**Comment by cwrau** [comment]
Ah, ok, so there is no way to set the global minimum logLevel aside from this environment variable?

**Comment by mjstrasser** [comment]
You can also:
- [Set `kloggingMinLogLevel` using the configuration DSL](https://klogging.io/docs/configuration/dsl#kloggingminloglevel).
- [Set `kloggingMinLogLevel` in a JSON / HOCON configuration file](https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/config/FileConfiguration.kt#L40) (missing from the documentation).

**Comment by mjstrasser** [comment]
Perhaps the DSL function and environment variable need a clearer name 🤔

**Comment by cwrau** [comment]
> You can also:
> 
> - [Set kloggingMinLogLevel using the configuration DSL](https://klogging.io/docs/configuration/dsl#kloggingminloglevel).
> - [Set kloggingMinLogLevel in a JSON / HOCON configuration file](https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/config/FileConfiguration.kt?rgh-link-date=2023-07-31T08%3A12%3A23Z#L40) (missing from the documentation).

Yes, but those are too late 😅

At that point, there are already log events sent by the internal logger;

> - [Set kloggingMinLogLevel using the configuration DSL](https://klogging.io/docs/configuration/dsl#kloggingminloglevel).

Sends this https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/config/KloggingConfiguration.kt#L60 before setting the level

> - [Set kloggingMinLogLevel in a JSON / HOCON configuration file](https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/config/FileConfiguration.kt?rgh-link-date=2023-07-31T08%3A12%3A23Z#L40) (missing from the documentation).

Sends this https://github.com/klogging/klogging/blob/main/klogging/src/jvmMain/kotlin/io/klogging/config/FindFileConfigText.kt#L38 before the setting the log level

**Comment by cwrau** [comment]
And while we're on the topic of setting minimum log levels for stuff, how do I set a minimum log level for a specific class?

I've tried 

```kotlin
    logging {
            fromLoggerBase(com.zaxxer.hikari.HikariDataSource::class.java.packageName, true)
            fromMinLevel(Level.ERROR) {
                toSink(stderr)
            }
        }
```

But the default

```kotlin
        logging {
            fromMinLevel(Level.INFO) {
                toSink(stdout)
            }
            fromMinLevel(Level.ERROR) {
                toSink(stderr)
            }
        }
```

also always matches and the `INFO` log just get's sent there instead of nowhere. Did I miss something?

**Comment by mjstrasser** [comment]
> Sends this https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/config/KloggingConfiguration.kt#L60 before setting the level

… and …

> Sends this https://github.com/klogging/klogging/blob/main/klogging/src/jvmMain/kotlin/io/klogging/config/FindFileConfigText.kt#L38 before the setting the log level

Ah yes, so they do. 

The `info()` calls on the internal logger are only made during configuration and only at application startup. The intention is to show whether Klogging started up correctly. After that, under default configuration, the internal logger is only called when something goes wrong with Klogging itself.

Why does it matter so much to you if Klogging sends a few ‘wayward’ messages at startup? Can your log events pipeline not handle them safely?

**Comment by mjstrasser** [comment]
> Or, asked more directly, is there a way to set the minimum log level per class / package / ...?

Will something like this work?

```kotlin
logging {
    // Match class exactly
    exactLogger("com.zaxxer.hikari.HikariDataSource")
    fromMinLevel(Level.INFO)
}
logging {
    // Package name (strictly: start of string)
    fromLoggerBase("com.zaxxer.hikari")
    fromMinLevel(Level.WARN)
}
```

**Comment by cwrau** [comment]
> > Sends this https://github.com/klogging/klogging/blob/main/klogging/src/commonMain/kotlin/io/klogging/config/KloggingConfiguration.kt#L60 before setting the level
> 
> … and …
> 
> > Sends this https://github.com/klogging/klogging/blob/main/klogging/src/jvmMain/kotlin/io/klogging/config/FindFileConfigText.kt#L38 before the setting the log level
> 
> Ah yes, so they do. 
> 
> The `info()` calls on the internal logger are only made during configuration and only at application startup. The intention is to show whether Klogging started up correctly. After that, under default configuration, the internal logger is only called when something goes wrong with Klogging itself.
> 
> Why does it matter so much to you if Klogging sends a few ‘wayward’ messages at startup? Can your log events pipeline not handle them safely?

I could probably just ignore those, but I'd like to keep everything clean and everything unnecessary turned off.

**Comment by cwrau** [comment]
> > Or, asked more directly, is there a way to set the minimum log level per class / package / ...?
> 
> Will something like this work?
> 
> ```kotlin
> logging {
>     // Match class exactly
>     exactLogger("com.zaxxer.hikari.HikariDataSource")
>     fromMinLevel(Level.INFO)
> }
> logging {
>     // Package name (strictly: start of string)
>     fromLoggerBase("com.zaxxer.hikari")
>     fromMinLevel(Level.WARN)
> }
> ```

Sadly no, the default I mentioned in https://github.com/klogging/klogging/issues/144#issuecomment-1657991725 still matches and the logs get sent there.

**Comment by mjstrasser** [comment]
> Sadly no, the default I mentioned in [#144 (comment)](https://github.com/klogging/klogging/issues/144#issuecomment-1657991725) still matches and the logs get sent there.

Maybe [`stopOnMatch`](https://klogging.io/docs/configuration/dsl#short-circuit-matching-with-stoponmatch) will help:

```kotlin
logging {
    // Match class exactly
    exactLogger("com.zaxxer.hikari.HikariDataSource", stopOnMatch = true)
    fromMinLevel(Level.INFO) {
        toSink("stdout")
    }
}
logging {
    // Package name (strictly: start of string)
    fromLoggerBase("com.zaxxer.hikari", stopOnMatch = true)
    fromMinLevel(Level.WARN) {
        toSink("stderr")
    }
}
logging {
    // Default, for unmatched loggers
    fromMinLevel(Level.INFO) {
        toSink("stdout")
    }
    fromMinLevel(Level.WARN) {
        toSink("stderr")
    }
}
```

Do you have other logging configurations?

(I realised that I left out the `toSink()` functions from the previous example.)

**Comment by cwrau** [comment]
I've tried around a lot and I came to the conclusion that the logging configuration is dependent on the order?!

When I set the "catch-all" logger configuration first all the other specific configurations don't work anymore.

But if I set it last then the `stopOnMatch` works.

Is this supposed to happen?

**Comment by mjstrasser** [comment]
> I've tried around a lot and I came to the conclusion that the logging configuration is dependent on the order?!

Yes. It is documented under [Short-circuit matching with `stopOnMatch`](https://klogging.io/docs/configuration/dsl#short-circuit-matching-with-stoponmatch):

<img width="764" alt="logging-function-order" src="https://github.com/klogging/klogging/assets/168173/91f2f449-eca2-4daa-b85b-b651980b83b6">

**Comment by mjstrasser** [comment]
Version 0.5.1 sends internal INFO messages after DSL or file-based configuration is read and applied. Let me know if it works for you.
