### ISSUE TITLE
Ability to provide api key when sending to Seq server

### ISSUE THREAD

**Issue by stevepentland** [klogging/klogging#153]
Hey there, I am trying to send some log events to a Seq server using the `seq` function in the config DSL. However it does not appear I am able to provide an API key when creating the sink. Is there another way to do this?

**Comment by mjstrasser** [comment]
Hi @stevepentland 

There is not yet a way to set a Seq API key but I should be able to add that pretty quickly.

**Comment by mjstrasser** [comment]
Version 0.5.3 now accepts Seq API keys and HTTPS endpoints.

**Comment by stevepentland** [comment]
Thank you @mjstrasser I will test it our shortly and let you know/close this issue!

**Comment by stevepentland** [comment]
Works as expected, thanks!
