### ISSUE TITLE
IntelliJ suggests imports from internal KLogging functions

### ISSUE THREAD

**Issue by tonisives** [klogging/klogging#170]
IntelliJ suggests me functions like these:

`launch` - conflicts with coroutines
`getenv` - conflicts with System.getenv

<img width="657" alt="Screenshot 2023-09-20 at 07 38 28" src="https://github.com/klogging/klogging/assets/1083534/271498b4-f8ee-4267-9b0a-b0981fb52348">

I don't know why it suggests these because they are actually internal

```kotlin
internal object SendingLauncher : CoroutineScope {

    override val coroutineContext: CoroutineContext
        get() = kloggingParentContext

    internal fun launch(block: () -> Unit) = launch(CoroutineName("SendingLauncher")) {
        block()
    }
}

```

Is it possible to turn these suggestions off?

Build #IC-223.7571.182, built on November 29, 2022

**Comment by mjstrasser** [comment]
Hi @tonisives, thanks for raising this issue.

[According to Kotlin docs](https://kotlinlang.org/docs/java-to-kotlin-interop.html#visibility), Kotlin `internal` maps to Java `public`. If your code is in Java then IntelliJ may suggest it, but your code is Kotlin so I wouldn’t expect that.

I will probably rename those functions, maybe next week when I have more time.

**Comment by tonisives** [comment]
Isn't this a problem with the IDE then? Maybe IntelliJ has some kind of configuration I can enable?

**Comment by mjstrasser** [comment]
I couldn’t find any configuration, nor any mention of it on [Kotlin Slack #intellij channel](https://kotlinlang.slack.com/archives/C0B8H786P), nor issues in [YouTrack for IntelliJ Kotlin plugin](https://youtrack.jetbrains.com/issues/KTIJ).

I don’t mind changing names if the new ones make sense to me.

**Comment by tonisives** [comment]
Did you try to reproduce the issue? I made a simple project with only KLogger and coroutines and I don't see this suggestion there.

Also, for my old project, I don't see the issue anymore.

Therefore it doesn't look like a problem anymore


<img width="943" alt="Screenshot 2023-09-26 at 08 41 19" src="https://github.com/klogging/klogging/assets/1083534/c3ce3b8b-a0be-45ed-a11d-e04e94220726">
