### ISSUE TITLE
Clarify message template implementation status

### ISSUE THREAD

**Issue by bddckr** [klogging/klogging#191]
The docs site says message templates still need to be fully implemented [here](https://klogging.io/docs/concepts/message-templates):
> [!NOTE]
> Message templates are partially implemented so far. It is planned to implement the standard more completely.

Is there any documentation on what's there vs. what's missing? I haven't found an issue tracking this, but I might have overlooked it.

Thanks for your work! Coming from a .NET background using Seq, and being used to good structured logging, I feel right at home with this library 😄

**Comment by mjstrasser** [comment]
Hi @bddckr, thanks for trying Klogging! 

In answer to your question about message templates, I checked the spec and how much I implemented. I have updated [the documentation](https://klogging.io/docs/concepts/message-templates) with details.

If there are features you want, please let me know or have a go yourself and submit a PR.
