### ISSUE TITLE
Default console logger should use STDERR, not STDOUT

### ISSUE THREAD

**Issue by christianhujer** [klogging/klogging#192]
The default logging currently is to STDOUT. It should be to STDERR. Logging to STDOUT is problematic when developing libraries that could potentially be used in programs that are designed to be used as pipes and filters, and it is problematic when developing pipes and filters. Imagine a program that generates a JPEG on STDOUT, to be processed downstream by something else, and that program logs a message. The JPEG image on STDOUT would be garbled with the log message.

**Comment by mjstrasser** [comment]
Hi @christianhujer, thanks for raising this issue and for your PR.

I am not convinced that logging should be to STDERR by default. Standard output and standard error streams exist for different purposes and I don’t see STDERR as the natural destination for most application logs. In many back-end service implementations it is usual to emit logs to STDOUT, where they are aggregated (by fluentd, for example) and sent to Splunk etc.

Thank you for your PR. I appreciate the creation of the new `STDERR_SIMPLE` and `STDERR_ANSI` sink configurations but am not convinced that `DEFAULT_CONSOLE` and `ANSI_CONSOLE` configurations should use them. I propose creating `DEFAULT_STDERR` and  `ANSI_STDERR` to provide simple-to-use configurations.

Klogging does not emit any application log events unless it is configured to do so. It should be easy to configure output to STDERR if that is what you need. 

Klogging also has its own [internal logger that sends log messages to STDOUT and STDERR, according to level](https://klogging.io/docs/internals/internal-logger). An example at startup is:
```
21:45:28.628949  INFO [                main] :        Configuration : Configuration read from file
```

These messages are sent independently of any application log events, and are always rendered using `RENDER_ANSI`. To stop any messages being sent to STDOUT, set `kloggingMinLogLevel` to `WARN` or `ERROR`, via the configuration DSL, file configuration, or the `KLOGGING_MIN_LOG_LEVEL` environment variable.
