### ISSUE TITLE
Gradle clean fails

### ISSUE THREAD

**Issue by binkley** [klogging/klogging#195]
Perhaps this is my environment, but hard for me to tell.
```
$ java --version
openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)

$ ./gradlew clean

> Configure project :
Reckoned version: 0.6.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'klogging'.
> Could not determine the dependencies of task ':convention-plugins:compileKotlin'.
   > Unknown Kotlin JVM target: 21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 604ms
```

**Comment by mjstrasser** [comment]
Hi Brian (@binkley)

Thanks for raising this issue. I was easily able to reproduce it by installing and using JVM version 21 to run Gradle.

The solution is to run Gradle 8.5 (Release Candidate or later) on JVM 21, or run earlier Gradle on JVM 19.

# Observations

Using Gradle 8.4, the dependencies for Kotlin compiler plugin are kept at version 1.9.10, which does not support JVM version 21. 

Here is a screen grab from a Gradle 8.4 scan.

<img width="559" alt="image" src="https://github.com/klogging/klogging/assets/168173/9956db57-7a98-42bd-9da9-b96dc1d99a6b">


Note that Klogging specifies version 1.9.20 of the Kotlin Gradle plugin. See [libs.versions.toml](https://github.com/klogging/klogging/blob/main/gradle/libs.versions.toml#L7) → [build.gradle.kts](https://github.com/klogging/klogging/blob/main/convention-plugins/build.gradle.kts#L11) → [klogging-kotlin-jvm.gradle.kts](https://github.com/klogging/klogging/blob/main/convention-plugins/src/main/kotlin/klogging-kotlin-jvm.gradle.kts#L20). (Same result for 1.9.21, by the way.) 

# Spelunking

I found this clue in the #gradle channel on Kotlin Slack:

<img width="740" alt="image" src="https://github.com/klogging/klogging/assets/168173/d7ea68a8-5406-4b27-8e74-35db10c21a24">

This sentence provided the solution:

> Technically you could already configure Gradle 8.4 to produce JVM21 bytecode, but the Gradle script itself couldn't be executed on a JVM21, that has changed now.

After installing Gradle wrapper 8.5-rc-4 as shown on the [Gradle Release Candidate page](https://gradle.org/release-candidate/), the build succeeded. Here is the snippet from that Gradle scan:

<img width="554" alt="image" src="https://github.com/klogging/klogging/assets/168173/1efc53e9-93bf-4a8b-9b65-05264cae5f78">

**Comment by binkley** [comment]
I'm facing similar upgrade issues moving my personal projects to JDK 21.

Here are my results for Klogging after upgrading Gradle wrapper.
I'm being verbose to hopefully help a Klogging dev:

```
$ ./gradlew wrapper --gradle-version latest  # Current as of this comment is Gradle 8.4
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Reckoned version: 0.6.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'klogging'.
> Could not determine the dependencies of task ':convention-plugins:compileKotlin'.
   > Unknown Kotlin JVM target: 21
```
Whoops! OK, I need to do this step-wise with an earlier JVM version to start from.
```
# Fiddle with my environment to use JVM 17
$ ./gradlew wrapper --gradle-version latest  # Current as of this comment is Gradle 8.4
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.1 (Amazon.com Inc. 21.0.1+12-LTS)
OS:           Linux 5.15.133.1-microsoft-standard-WSL2 amd64
# Undo my environment changes, go back to JVM 21
$ ./gradlew wrapper --gradle-version latest

> Configure project :
Reckoned version: 0.6.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'klogging'.
> Could not determine the dependencies of task ':convention-plugins:compileKotlin'.
   > Unknown Kotlin JVM target: 21
```
OK, that isn't right. JVM 21 should be supported by Kotlin 1.9.20+.

Am I doing something silly, or missing a step?

**Comment by binkley** [comment]
One quirk I noticed with Gradle versions.
The current HEAD as of this comment for Gradle version is 8.4. That does not build for me with JVM 21.

When I moved to 7.6.3, Klogging does build using JVM 21.

**Comment by mjstrasser** [comment]
Gradle 8.5 has been released. 

Klogging has been updated to use Gradle wrapper 8.5 and now builds on Java 21.
