### ISSUE TITLE
Structured logging without string message

### ISSUE THREAD

**Issue by justinc-patchwork** [klogging/klogging#209]
Hi,
Firstly, thank you for your library. This is not an issue with existing functionality but more of a question.

Currently, to get structured json logging, we have to use a message template, that requires creating a string message with placeholders, then including values for the placeholders in subsequent arguments.

Is there a way (or a reason not ) to only have the structured part of the log, so I'm not having to repeat the data in both the string message and the object?

eg instead of `logger.info("something about {user}, {email}, {dob}", user, email, dob)`, 
I can just use `logger.info(userid, email, dob)`

**Comment by mjstrasser** [comment]
Hi @justinc-patchwork, thanks for using Klogging! 

Thanks for your question. I hadn’t considered simply adding objects to log events. Klogging’s heritage is a combination of Java logging (Log4j and Logback) and .NET logging (especially Serilog). In all those cases, there is always a string message emitted to summarise what happened at that point. All log aggregators I have used (Splunk, ELK, AWS CloudWatch and Seq) show one-line messages for log events.

One thing to consider with your proposal is that a log event is essentially a Kotlin `Map<String, Any>` so every entry needs a `String` key. In your example, `logger.info(userid, email, dob)`, how does Klogging derive the names of the keys for the map? It is not feasible to use reflection to get the local names.

Perhaps accepting a list of `Pair`s, like `logger.info("userid" to userid, "email" to email, "dob" to dob)` might work, but there is still the question of what goes into a string message. This is where I think [message templates](https://messagetemplates.org) are useful.

**Comment by justinc-patchwork** [comment]
Thanks for the response. I understand your points.
