### ISSUE TITLE
Evaluate templates in simple string rendering

### ISSUE THREAD

**Issue by mjstrasser** [klogging/klogging#21]
# Background

Klogging includes a simple implementation of [message templates](https://messagetemplates.org) that works when events are dispatched to a [Seq server](https://datalust.com/seq). 

For example, from this log statement:

```kotlin
    val user = "Samuel"

    logger.info("User {name} logged in", user)
```

Klogging sends a CLEF event including template and value for the hole `user`:

```json
{
  "@mt": "User {name} logged in",
  "user": "Samuel"
}
```

Seq fills in the template and displays something like:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/168173/127983414-1c02c9bd-1be7-4a7c-8ecf-e8c3e2fb0f55.png">

But other sinks do not fill in the template. The `RENDER_SIMPLE` renderer emits the raw template:

```
2021-08-03 18:24:29.188021 INFO [main] Playpen {user=Samuel} : User {user} logged in
```

# Enhancement

Enhance other renderers to fill in templates, starting with `RENDER_SIMPLE` so it will output `User Samuel logged in` instead of `User {user} logged in`.

**Comment by binkley** [comment]
I was looking at the example, and had two opposite styles in mind for substitution:

1. The "{someVar}" style common with several other logging frameworks -- upside: Consistency with others
2. The "$someVar" style that Kotlin itself uses -- upside: Consistence with Kotlin

I lean towards \#2 to emphasize this is a _Kotlin_ logging library.  But then I realized, hmm ... won't the Kotlin compiler try to interpolate the strings, so you'd need to escape the dollar signs! :(

I see why you went with \#1.
