### ISSUE TITLE
Allow for custom sink file-based configuration

### ISSUE THREAD

**Issue by chile12** [klogging/klogging#211]
Less of an issue and more a small feature request:

Currently custom sinks have to be configured via DSL
```
loggingConfiguration(append = true) {
    sink("SINKNAME", MySink())
}
```
Which divides the configuration into a json-file and this DSL appendix, at least in my case.
Therefore, a simple registry, where we could register Sink types based on an identifier, would be a great addition.

Cheers,

**Comment by chile12** [comment]
Good start ;)
I would suggest going all the way, though:
```
"sinks": {
  "XRender": {
    "render": "com.example.render.XRender",
    "sender": "STDOUT"
  },
  "OTSink": {
    "render": "com.example.render.OpenTelemetryLogRecord",
    "sender": "com.example.render.OpenTelemetryEventSender"
  }
}
```
How about that?

**Comment by mjstrasser** [comment]
I have created some code for named renderer and sender classes. You can try them in the latest `0.6.0-SNAPSHOT` release of Klogging.

I haven’t written docs yet but you need classes like these:

```kotlin
package com.example.logging

import io.klogging.rendering.Renderer
import io.klogging.rendering.RenderString
import io.klogging.sending.Sender
import io.klogging.sending.StringSender

class MessageOnlyRenderer : Renderer {
    override fun renderString() : RenderString = { event ->
        event.message
    }
}

class RabbitHoleSender : Sender {
    override fun sendString() : StringSender = { str ->
        downTheRabbitHole(str)
    }
}

```

These classes are loaded using no-argument constructors, which might prove limiting if you need them to have access to state. At this stage they are experimental.

Let me know what you think.

**Comment by chile12** [comment]
Looks great, I'll have a go with it. Thank you

**Comment by mjstrasser** [comment]
This change and bugfix #218 are in release 0.5.8.

**Comment by chile12** [comment]
Hi again, so I tried it out.

Unfortunately we talked cross purposes, I actually need an EventSender, handling LogEvents.
In this context, is it possible to open up the LogEvent class, currently I have to workaround inserting internal properties in the items map.
May I suggest expanding this to include EventSender classes: (never worked with Gradle, so I dont trust myself to create a fork)

```kotlin
public data class FileSinkConfiguration(
    val renderWith: String? = null,
    val sendTo: String? = null,
    val seqServer: String? = null,
    val apiKey: String? = null,
    val checkCertificate: Boolean? = null,
    val splunkServer: SplunkEndpoint? = null,
    val renderHec: RenderHec? = null,
    val eventSender: String? = null,
) {
    internal fun toSinkConfiguration(): SinkConfiguration? {
        val renderer = builtInRenderers[renderWith]
            ?: loadRendererByName(renderWith)
            ?: renderHec?.renderer
        if(eventSender != null){
            when(val eventSender = loadEventSenderByName(eventSender)){
                null -> warn("File Configuration", "EventSender $eventSender not found in classpath!", null)
                else -> return SinkConfiguration(eventSender = eventSender)
            }
        }
        if (splunkServer != null) {
            return SinkConfiguration(eventSender = splunkHec(splunkServer.evalEnv(), renderer ?: renderHec()))
        }
        if (seqServer != null) {
            return seq(
                evalEnv(seqServer),
                apiKey?.let { evalEnv(it) },
                checkCertificate ?: true,
                renderer ?: RENDER_CLEF,
            )
        }
        val sender = builtInSenders[sendTo]
            ?: loadSenderByName(sendTo)
        return if (renderer != null && sender != null) {
            SinkConfiguration(renderer, sender)
        } else {
            null
        }
    }
```

**Comment by mjstrasser** [comment]
Hi @chile12 

The latest snapshot builds of Klogging specify an interface called `EventSender` that can be implemented by a class on the classpath.

```kotlin
public interface EventSender {
    public operator fun invoke(batch: List<LogEvent>)
    public operator fun invoke(event: LogEvent) {
        invoke(listOf(event))
    }
}
```

Name the class in JSON, for example:
```json
"sinks": {
  "custom": {
    "eventSender": "com.example.CustomEventSender"
  }
}
```

**Comment by mjstrasser** [comment]
Here is a silly example I created, to prove that it works:
```kotlin
class Mirror : EventSender {
    override fun invoke(batch: List<LogEvent>) {
        batch.forEach { println("${it.message}<==>${it.message.reversed()}") }
    }
}
```

**Comment by chile12** [comment]
Looks great, I assume this will crop up in the next tag release?
Also what do you think about opening data class `LogEvent` ?
Sorry for all the suggestions ;)

**Comment by mjstrasser** [comment]
Yes, and I am going to refactor both `RenderString` and `SendString` to be interfaces with `operator fun invoke()` functions to get consistency. The recent `Renderer` and `Sender` interfaces will go away. Sorry for the inconvenience (I assume that only you would be using those interfaces at this stage).

What is your use case for opening up `LogEvent`? What do you want to add to it?

**Comment by chile12** [comment]
Well in my specific use case I have to pass along the Open Telemetry context (which changes with every service call):

```kotlin
        context (CoroutineScope)
        suspend fun traceableLogEvent(event: LogEvent): LogEvent {
            val scope = this@CoroutineScope
            return LogEvent(
                    getId(event.logger),
                    event.timestamp,
                    event.host,
                    event.logger,
                    getContext(scope),
                    event.level,
                    event.template,
                    formatMessage(event.message, event.items),
                    event.stackTrace,
                    // extend items with the current Context as a workaround -> needs to be removed before emitting to Sink
                    event.items.plus(OpenTelemetryContextKey to scope.coroutineContext.getOpenTelemetryContext())
            )
        }
```

**Comment by mjstrasser** [comment]
Klogging can [map information from other coroutine contexts](https://klogging.io/docs/context/other-coroutine-context). Would that do what you want?

It can also [add items from any other source](https://klogging.io/docs/context/other-context).

**Comment by chile12** [comment]
@mjstrasser While I think that is a step in the right direction, decoupling the sink from the context chain is the main issue. Otherwise, I could just reuse the context within my Sink and pass along anything I'd please.

This is the location in the Sink class where a new Context is created (and not reused)
```kotlin
    private val sinkChannel: Channel<LogEvent> by lazy {
        debug("Sink", "Starting sink $name")
        val channel: Channel<LogEvent> = Channel(sinkChannelCapacity)
        launch(CoroutineName("sink-$name")) {
```

**Comment by mjstrasser** [comment]
@chile12 I am not sure what you are trying to achieve and maybe you misunderstand the role of sinks.

By the time a log event is emitted, it should have all the information it needs, including context at the time it occurred. It should not need any context from sinks.

Sinks only exist to move log events to some destination. They create channels to decouple event dispatching from sending. Maybe this diagram on [Klogging internal process](https://klogging.io/docs/concepts/klogging-process) makes this a bit clearer:

![Klogging process diagram](https://klogging.io/img/klogging-process.svg)

**Comment by chile12** [comment]
I understand, I do actually need the context within the sink, but this is not an issue of Klogging.
I will continue propagating in within the items map, which works just fine.

Thank you, the eventsender mechanic is great though; I'm closing this issue.
