### ISSUE TITLE
loggerFor(...) resets sink configuration

### ISSUE THREAD

**Issue by chile12** [klogging/klogging#232]
When creating a new Logger, the loggerFor function(s) call `KloggingEngine.configuration` causing the reloading of the file config, resetting the sink configuration with sinks in the config file, overriding any sinks defined via DSL. I assume this holds true for any DSL-set property.

Am I doing anything fundamentally wrong in my approach? Or is there a hook with which to set DSL configuration?

---------------------
Some further research revealed:
Since `KloggingEngine.configuration` is a lazy val, you have to make sure to create at least one logger before using any DSL configuration, otherwise the initial call will overwrite you DSL-set properties, as described above.

**Comment by mjstrasser** [comment]
Hi @chile12, thanks for raising this. 

I made some early decisions about using lazy evaluation to load things into memory only if needed. I know there is a strange interaction between DSL and file configuration and have been meaning to sort this out.

Hopefully in the next day or so I will have a plan.

**Comment by mjstrasser** [comment]
The core issue is that Klogging needs to find configuration files on the classpath or specified explicitly. That configuration is called by the singleton `KloggingEngine` object but it can’t search for them before it is fully initialised. (Trying to do that fails with `java.lang.ExceptionInInitializerError`.)

Either Klogging needs some kind of `initialise()` function that must be called before it is used, or files are searched in response to lazy evaluation of a property (as now).

The most recent change calls the lazy evaluation at the beginning of configuration DSL processing as well as in `loggerFor()` functions.

This means that any file configuration is always loaded before any DSL configuration. The options are:

- Only DSL: no configuration file is loaded and the DSL configuration is used.
- Only files: configuration is loaded from file when the first logger is declared.
- Files and DSL: configuration is loaded from file immediately before the DSL is processed, or the first time a logger is declared (whichever comes first). The DSL configuration will replace file configuration unless it specifies `loggerConfiguration(append = true)`.

That is the best I can do for now. I hope you can work with it this way.

**Comment by mjstrasser** [comment]
Klogging release 0.5.11 contains the updated code.
