### ISSUE TITLE
HOCON substitutions do not work

### ISSUE THREAD

**Issue by gavvvr** [klogging/klogging#235]
Hello. I would want to use HOCON for configuring Klogging because of the flexibility this format provideы.
I am used to it since I started using Ktor, which allows using HOCON for configuring Ktor apps.

Right now I'm creating a shared component with shared configuration for my JVM-based services.
Basically I want to:
1) have some base configuration with sensible defaults in a shared jar
2) allow overriding those defaults with another `conf` file on classpath (will be located in `src/main/resources` of each individual app).

So, imagine the base config looks like the following (notice the `include` for overrides in the end):

```hocon
sinks {
    stdout {
        renderWith = RENDER_ANSI
        sendTo = STDOUT
    }
}
logging = [
    {
        levelRanges = [
            {
                fromMinLevel = INFO
                toSinks = [stdout]
            }
        ]
    }
]

include classpath("klogging-app.conf")
```

and suppose the consumer of this base config would want to enable DEBUG logs for MongoDB driver (`klogging-app.conf` in `src/main/resources` of some specific app):

```hocon
logging += // adding one more element to 'logging'
{
  fromLoggerBase = org.mongodb
  levelRanges = [
    {
      fromMinLevel = DEBUG
      toSinks = [stdout]
    }
  ]
}
```

There is no problem with `include`, it works. The problem is with `+=` syntax, which is a part of ["substitutions" syntax](https://github.com/lightbend/config/blob/v1.4.3/HOCON.md#the--field-separator).

Basically no substitutions work right now and they fail with the following error:
```
com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs
```
The same error will happen if you simply try to substitute a variable in a single file:
```hocon
foo = foo
bar = ${foo}
```
I would also want to use such substitution to allow enabling structured logging on deployment, but stick with ANSI by default for readability in 'development mode'. My config would look like the following to allow this override with the `RENDER_LOGS_WITH` env var:
```hocon
sinks {
    stdout {
        renderWith = RENDER_ANSI
        renderWith = ${?RENDER_LOGS_WITH}
        sendTo = STDOUT
    }
}
```

I did some research and to me it looks like it's a problem of a kotlinx.serialization library you use to parse HOCON (which has experimental support of HOCON for now). I've created an issue Kotlin/kotlinx.serialization#2564, but at the same time I am not sure it makes sense to continue using it for parsing Klogging config since it seems to be very limited.
You can consider using [config4k](https://github.com/config4k/config4k) project for easy mapping of HOCON configs to Kotlin data classes or simply use raw Typesafe's Config (like [Ktor does](https://github.com/ktorio/ktor/blob/2.3.7/ktor-server/ktor-server-core/jvm/src/io/ktor/server/config/HoconApplicationConfig.kt#L7))

**Comment by mjstrasser** [comment]
Hey @gavvvr, thanks for raising this. Sorry the HOCON handling is so limited.

I will probably switch to using Typesafe Config like Ktor, but I don’t know when that might be.

**Comment by gavvvr** [comment]
Hi @mjstrasser 
Looks like my assumption about HOCON support in kotlinx.serializtion project was incorrect. Calling `.resolve()` before passing an input into kotlinx decoder solves the problem. I've prepared a PR.
