### ISSUE TITLE
RENDER_ECS feature request: Include message template in the output

### ISSUE THREAD

**Issue by hoylu-royberg** [klogging/klogging#265]
Similarly to `@mt` with `RENDER_CLEF` renderer, it would be very useful to have the message template for the `RENDER_ECS` renderer as well.

**Comment by mjstrasser** [comment]
Hi @hoylu-royberg I think that is feasible.

**Comment by mjstrasser** [comment]
It is possible but I am curious as to why you want the template as well as the rendered message.

The [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/ecs-reference.html) does not define a `template` field, but it could be added under `labels`.

Actually, looking at the how `RENDER_ECS` works, mapped items should be under `labels`. It currently puts some under `items`, which is not part of ECS.

**Comment by hoylu-royberg** [comment]
Hi Michael,

When investigating an issue (e.g. a bug) we find it helpful to filter by the log message template in Elastic, because the bulk of our log statements have one or more structured log elements (for instance identifiers or timing info), so filtering by the rendered log message is then less useful if one is trying to look at the bigger picture.

For our .NET based services we use [an official ECS formatter from Elastic team](https://github.com/elastic/ecs-dotnet/tree/main/examples/aspnetcore-with-serilog), and as you can see it produces a log output that is surprisingly quite different than what their own ECS reference documentation states. For example structured log elements are put under `metadata`, not `labels`.

**Comment by mjstrasser** [comment]
Thanks for clarifying. It seems there are many shades of ECS (and it seems you can put whatever you like outside `@timestamp` and `message`).

I have created a `RENDER_ECS_DOTNET` renderer that will hopefully do what you want. It is in the new 0.5.14 release.

You can also [create your own renderer class](https://klogging.io/docs/concepts/rendering-and-sending#custom-rendering-and-sending) and specify its fully-qualified name in your configuration.
