### ISSUE TITLE
Logger-specific context

### ISSUE THREAD

**Issue by realdadfish** [klogging/klogging#274]
I recently stumbled upon your library and figured I give it a try and not roll my own logging infrastructure this time in my new project :)

The library seems very well designed from what I can see, one small feature is however missing for me (which I hand-rolled usually), namely the ability to create child loggers that derive the context configuration of the global / parent logger.

Now, configuration is detached and globally available as it seems (the global "baseContext"), so I don't know how feasible to implement it in the current architecture, but this is something that I actually miss.

Use cases would include the enrichment of logging context for worker instances of any sort (async processing, HTTP requests, ...), the scoping of UI-specific loggers (to always know "on which screen" a particular logging action resulted from) and so on and so forth. The logger's class name is the only way to group / tag things a little, but I think it's ugly to misuse that field for contextual purposes.

If I skip the idea of "deriving" context, maybe adding log-specific (non-derived) context could also already help, by creating an overload for the `logger(...)` and `noCoLogger(...)` methods that would accept then a `vararg context: Pair<String, Any?>`.

**Comment by mjstrasser** [comment]
Hi @realdadfish, thanks for trying Klogging and for creating this issue.

## Logger context

I am interested that you want loggers to have their own context. In Klogging log _events_ have context items (`Pair<String, Any?>`) at the time they occur. Context comprises:

- [Base context](https://klogging.io/docs/context/base-context): items present for the lifetime of the application. They are included in events created by `Klogger` and `NoCoLogger` instances.
- [Coroutine log context](https://klogging.io/docs/context/coroutine-context-items): items put into `LogContext` in the current coroutine context. They are included in events by `Klogger` instances using `suspend` logging functions (but not `NoCoLogger` instances). They are copied into child coroutine contexts.
- [Other coroutine context](https://klogging.io/docs/context/other-coroutine-context): items can be copied from other coroutine contexts, like Project Reactor.
- [Items copied from non-coroutine contexts](https://klogging.io/docs/context/other-coroutine-context), like MDC.
- [Fields in log message templates](https://klogging.io/docs/context/message-templates).
- [Items sent in logging function calls](https://klogging.io/docs/context/immediate-context-items).

(I am improving [the documentation](https://github.com/klogging/klogging.io) to make this clearer – suggestions welcome.)

Could that cover what you need?

## Parent–child loggers

Loggers in Klogging have no relationship to each other. Log4j and Logback are the only logging systems I have seen where names connote relationships (e.g. a logger called `com.example.service` is a parent of one called `com.example.service.prices`). I am not sure I like that kind of implied and perhaps surprising relationship.

(In Klogging, [selecting loggers by name](https://klogging.io/docs/configuration/dsl#fromloggerbase-exactlogger-and-matchlogger) to decide whether to emit log events can imply relationships between loggers.)

An explicit relationship between loggers could be created something like this:

```kotlin
class Parent {
    val logger = logger<Parent>()
    // etc.
}
class Child {
    val logger = logger<Child>(parent = Parent.logger)
    // etc.
}
```

As I understand your question, the need for these relationships is when loggers have some items assigned to them.

**Comment by realdadfish** [comment]
Hi @mjstrasser, thanks for your reply. So, to answer your questions

> Logger-specific contexts

The thing for me (at least) is that while the coroutine context case is a very smart way to log things running in such a specific context, this kind of mixes two different concepts, the technical concept of having a "context" for a coroutine that carries technical information about coroutine execution, with a logical "context" of having an application component that has it's own logging needs, regardless _how_ it actually executes it's code.

To make things more clear, I wrote a small abstraction and decided to use the NoCoLogger implementation, just because I do _not_ want to enforce the usage of coroutines in any part of my application. That the underlying logging system uses coroutines itself for me is an implementation detail and I want to use the same logging instance in and outside of a coroutine context. Which, in return, makes the proposed use of a "coroutine context" for additional logging data not viable.

And all the other context options you provided are totally fine for me and useful as-is, but not for my "give component-specific context without enforcing the execution context" type of use case.

> Parent–child loggers

I agree that package-level relationships are a bad idea, because their implicit magic instead of explicit configuration. My main use case for a relational logger is really context-copying. I understand that `logger<Child>(parent = Parent.logger)` is not possible yet (can't see it in code), but yes, this would go into the right direction. Ideally, a child logger would be created with a function from the parent logger and also immediately accept logging context itself (see above), and to make this explicit, one could do something like this:

```
class Child {
    val logger = logger<Child>(context = parent.context + mapOf(/* new context */))
}
```

if the context (and this is my main concern) should be the only thing that "defines" such a relationship.

**Comment by mjstrasser** [comment]
Thanks for the clarification. I’ll have a look at it.

**Comment by mjstrasser** [comment]
First changes are in (I forgot to add #274 to the commit messages). You can add context items to a logger and they will be included in log events.

Copying from one logger to another coming soon.

**Comment by mjstrasser** [comment]
First pass of documentation is here: https://klogging.io/docs/context/logger-context-items

**Comment by realdadfish** [comment]
Many thanks for the quick implementation!
