### ISSUE TITLE
Publish multiplatform publications successfully

### ISSUE THREAD

**Issue by mjstrasser** [klogging/klogging#294]
Thanks to @kvaster for PR #291, Klogging is starting towards being multiplatform.

The publish steps did not work, because of a Gradle error:

`Reason: Task ':klogging:publishAndroidReleasePublicationToSnapshotsRepository' uses this output of task ':klogging:signJsPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.`

[This build](https://github.com/klogging/klogging/actions/runs/10643003697/job/29506068883) is an example.

**Comment by mjstrasser** [comment]
[This Gradle build scan](https://scans.gradle.com/s/sxm4obihb2hiu) from a local attempt provides more detail.

**Comment by mjstrasser** [comment]
Is [build.gradle.kts](/klogging/klogging/blob/main/klogging/build.gradle.kts) set up correctly?

On [Gradle Slack](https://gradle-community.slack.com/archives/CAHSN3LDN/p1723797152202269?thread_ts=1723787125.804569&cid=CAHSN3LDN) I saw this advice about this type of error:

> This error usually happens when tasks are having overlapping outputs

**Comment by kvaster** [comment]
I will try to look on this today. Signing was a little bit specific and I was testing only the code itself.

**Comment by kvaster** [comment]
This problem is described here: https://github.com/gradle/gradle/issues/26091#issuecomment-1836156762
It looks like removing javadoc stub, which is the same for all targets, solves problem. Maybe this stub is not needed ?
