### ISSUE TITLE
Create single object with Klogging state

### ISSUE THREAD

**Issue by mjstrasser** [klogging/klogging#30]
There is a single Kotlin `object` with state of Klogging in a running application. It contains properties with holders for values that can be safely mutated.

Properties to include:

* MInimum log level for Klogging
* Current configuration in a `KloggingConfiguration` (as class) isntance
* Coroutine dispatcher(s) used by Klogging

**Comment by binkley** [comment]
Nice.  This would set Klogging up for eventually supporting user-supplied/maintained context that is non-global.  So, for example, a service gateway could send one kind of logging back towards the inside of the bounded domain, and a different kind of logging outwards to an aggregator service, ala hexagonal architecture.

**Comment by mjstrasser** [comment]
First version of this is working.
