### ISSUE TITLE
Formatting: Logger name compression & thread names

### ISSUE THREAD

**Issue by waltkb** [klogging/klogging#306]
When using `RENDER_ANSI`, is it somehow possible to increase the maximum width before the compression of the logger name to shortened strings kicks in (e.g. `o.m.d.p.command`)?

And on the other hand, is there some option to reduce the maximum width of the thread name? (e.g. for thread names like` [                main] : ` or ` [            Thread-9] ` there is a lot of space, which I'd rather like to use for the logger name instead)

**Comment by mjstrasser** [comment]
Hi @waltkb, thanks for your issue.

I will look into ways to easily customise how those log outputs are created, hopefully in the next week.

**Comment by mjstrasser** [comment]
@waltkb Finally I have found time to look into this. Sorry it has taken a while.

As a first step, I have implemented the function `renderAnsi(contextWidth: Int, loggerWidth: Int)` that can be called from the configuration DSL. An example might be:

```kotlin
loggingConfiguration {
    sink("console", 10, 30)
    logging {
        fromMinLevel(Level.INFO) {
            toSink("console")
        }
    }   
}
```

With output like this:
```
22:01:19.809992  INFO [Dispatcher] :     com.example.KloggerPlaypen : Run 5
````

If the values of `contextWidth` of `loggerWidth` is less that 1, that field is not included.

I do not have a JSON or HOCON representation of the function yet.

**Comment by mjstrasser** [comment]
@waltkb Version 0.8.0 of Klogging is released with flexible pattern-based formatting, available using the DSL or from JSON or HOCON files.

I will update the documentation soon, but here is a JSON example:

```json
{
  "sinks": {
    "console": {
      "renderPattern": "%t{LOCAL_TIME} %-5v{COLOUR} [%-15c] : %-25l : %m : %i%s",
      "sendTo": "STDOUT"
    }
  },
  "logging": [
    {
      "fromMinLevel": "INFO",
      "toSinks": [ "console" ]
    }
  ]
}
```

Fields are specified by `%[SIZE]X[{FORMAT}]` where:

- X is a field of a log event:
   - `t`: timestamp
   - `v`: level
   - `c`: context
   -  `l`: logger
   - `m`: message
   - `i`: items
   - `s`: stack trace (if present)
   - `n`: output a newline
- SIZE is optional and specifies:
   - Width of most fields. If the value is narrower than the width, it is space-padded to fit: left-aligned for positive SIZE
     and right-aligned for negative SIZE. If SIZE is zero the field is not output.
   - For stack trace, the maximum number of lines to output.
- {FORMAT} (including braces) is optional. These values are currently available:
   - `%v{COLOR}` or `%v{COLOUR}` to output different colours for different levels.
   - `%t{LOCAL_TIME}` to output only the time portion of timestamps, in the local timezone.

Please let me know if you try it and how it goes.

**Comment by mjstrasser** [comment]
[The documentation](https://klogging.io/docs/configuration/pattern-rendering/) is now published.
