### ISSUE TITLE
Discuss `LogEvent.id`

### ISSUE THREAD

**Issue by binkley** [klogging/klogging#35]
Current `LogEvent.id` field defaults to `Random.nextULong().toString(16)`

Considerations:
1. Use an auto-incrementing value.  See chat discussion
2. Use a UUID.  This is a common choice
3. Consider ULID alternative to UUID.  See https://github.com/ulid/spec and chat discussion
4. Require caller to initialize Klogging with a strategy for identifiers

**Comment by mjstrasser** [comment]
The choice of default value for `LogEvent.id` was deliberate.

I wanted a _compact_, random-enough identifier to use in tracing Klogging internal logs.

1. Auto-incrementing may be useful, e.g. if the order in which log events are created becomes important.
2. UUIDs are long, even after you take out the dashes. Global uniqueness is not important.
3. I like the look of ULID but they are still long and require an external library.
4. Requiring a strategy smells like YAGNI at this point.

Fun facts: 

- The very first event model did not have an ID. 
- I added `val id: String` to it, with a multiplatform `newId()` function that returns a random UUID on JVM (commit dec898101e0501f36ed4b2ccf2362f327c633d95). 
- I didn’t see a lot of use for it so I removed it later (commit d00f555cd4415a74d0f54e09ffaa5b3ef9fbe7ab). 
- I only added back the property to help with following Klogging itself using the internal logger (commit b389b396cb9303db684b5c7e5487912cdfa5d5ca).
