### ISSUE TITLE
Create a renderer for Elastic Common Schema (ECS)

### ISSUE THREAD

**Issue by mjstrasser** [klogging/klogging#38]
Create an implementation of `RenderString` that generates JSON compatible with [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/index.html) for ease of shipping to [ELK](https://www.elastic.co/what-is/elk-stack) implementations.

**Comment by GinGin3203** [comment]
Guess I'll grab it
Could you assign the issue pls?

**Comment by Pihanya** [comment]
@mjstrasser, this issue was implemented in [elkSender.kt](https://github.com/klogging/klogging/blob/0.4.1/src/jvmMain/kotlin/io/klogging/sending/elkSender.kt) and [SendElk.kt](https://github.com/klogging/klogging/blob/0.4.1/src/commonMain/kotlin/io/klogging/sending/SendElk.kt), wasn't it?

**Comment by mjstrasser** [comment]
@Pihanya Yes, I did the rendering part in [RenderEcs.kt](https://github.com/klogging/klogging/blob/main/src/commonMain/kotlin/io/klogging/rendering/RenderEcs.kt).

I tried to implement sending to a local ELK stack over HTTP but couldn’t get it to ingest messages directly (i.e. not using Logstash or Beats). I found the whole ELK setup bewilderingly complex compared to Seq and Splunk.
