### ISSUE TITLE
Enchance performance of `RENDER_GELF` 

### ISSUE THREAD

**Issue by GinGin3203** [klogging/klogging#43]
Currently `RENDER_GELF` fills in `GELF_TEMPLATE` with chained calls of `.replace`, which isn't really necessary as render functions are only invoked inside synchronous environments (AFAIK; I may be wrong, but the only place I've found where they are invoked is the `Dispatcher` object inside individual coroutines), so there isn't a hard requirement for immutability and the functionality can be implemented with `StringBuilder` or Kotlin string interpolation ([which is actually also a `StringBuilder`](https://www.baeldung.com/kotlin/string-interpolation)), which is better than multiple copyings from a performance perspective

This is a minor issue, but I thought that it would be a good idea to document it

**Comment by mjstrasser** [comment]
Thanks @GinGin3203 for your issue. I agree it is sub-optimal: it was just a first go to show it can be done.

Please submit a PR if you want to improve `RENDER_GELF`.
