### ISSUE TITLE
Thread.sleep() necessary to see the logs?

### ISSUE THREAD

**Issue by jmfayard** [klogging/klogging#65]
Given this main function

```kotlin
fun main() {
    loggingConfiguration {
        DEFAULT_CONSOLE()
    }
    val logger = noCoLogger("Log")
    logger.info("Hello World")

    /** Uncomment to see the log: INFO [main] Log : Hello World **/
    // Thread.sleep(100)
}
```

I expect to see:

```
12:46:55.381571  INFO [                main] :        Configuration : Setting configuration using the DSL with append=false
2022-03-01 12:47:19.539911 INFO [main] Log : Hello World
```

but I see

```
12:46:55.381571  INFO [                main] :        Configuration : Setting configuration using the DSL with append=false
```

If I uncomment the `Thread.sleep(100)`, I see both lines.

What I am missing?

**Comment by mjstrasser** [comment]
@jmfayard Thanks for looking at Klogging!

In a simple, straight-through main program, you need to wait for logs, by calling either `Thread.sleep()` or with a coroutine `delay()`. 

I could not find a way to get an exiting program to wait for the Klogging coroutines to dispatch and send all messages. I will add that to the documentation.

**Comment by mjstrasser** [comment]
See [Direct logging](https://klogging.io/docs/concepts/direct-logging) for a recent feature that causes logs to be sent directly to sinks instead of via coroutines.
