### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by binkley** [klogging/klogging#7]
This is more a matter of personal taste.  More open source projects use a package naming scheme corresponding roughly to a reversed FQDN domain name.

So perhaps, `org.klogger` rather than just `klogger`?

I also note that the domain name, "klogger.org", is not taken.

**Comment by mjstrasser** [comment]
Thanks @binkley 

I have a distaste for long package names just because someone thought is was a good idea in 1993. I had hoped that Kotlin might break away from that Java baggage.

However for an open-source library a short domain base package related to an actual domain is useful.

**Comment by mjstrasser** [comment]
Done!
