### ISSUE TITLE
Call log methods, without checking whether the respective log level is enabled

### ISSUE THREAD

**Issue by qoomon** [klogging/klogging#75]
Would be nice if you add support for lazy API as well e.g. `logger.debug { "Some $expensive message!" }`
```kotlin
fun debug(msg: () -> Any?) {
    if(isDebugEnabled)  debug(msg().takeIf { it != Unit }?.toString().orEmpty())
}
```

**Comment by mjstrasser** [comment]
@qoomon Thanks for your question.

Klogging does support lazy API, in both the coroutine `Klogger` and non-coroutine `NoCoLogger` versions.

I wrote an explicit test for it here: https://github.com/klogging/klogging/blob/e73ec3074e0c038fb39805fad358a382d1fe9ed6/src/jvmTest/kotlin/io/klogging/KloggerTest.kt#L186

**Comment by qoomon** [comment]
Oh, that's great then, I missed that. I think the examples in the readme should use this lazy syntax, because this should be the preferred way of logging. Especially for expensive debug logging.

And thanks for starting a new nativ logging Framework for kotlin.
