### ISSUE TITLE
Exception when using any type of log

### ISSUE THREAD

**Issue by russellbanks** [klogging/klogging#76]
Whenever I use any type of log in my application, I get this exception below. For context, it is a Compose for Desktop application. I have tried defining the logger both through an interface and directly and they all cause this same crash once any log tries to be run.

```
Exception in thread "DefaultDispatcher-worker-1" java.lang.IncompatibleClassChangeError: Found interface kotlin.time.TimeMark, but class was expected
	at io.klogging.sending.BatchingKt.receiveBatch(Batching.kt:48)
	at io.klogging.internal.Sink$sinkChannel$2$1.invokeSuspend(Sink.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(sink-console), StandaloneCoroutine{Cancelling}@5415e1fd, Dispatchers.Default]
```

**Comment by mjstrasser** [comment]
Hi @russellbanks, thanks for raising this issue. I will look into it during the next day. 

Are you trying Klogging with your HashHash application?

**Comment by russellbanks** [comment]
> Are you trying Klogging with your HashHash application? 

Yes, I'm happy to make a branch and reproduce the issue there if it helps?

**Comment by mjstrasser** [comment]
Yes please, that will help. I am unfamiliar with Compose for Desktop. Does it work with Kotlin/JVM? (Klogging only supports JVM right now.)

I will try to have a look tonight (it is just after 5pm here.)

An initial thought I have is that the code in question uses experimental coroutines and time APIs, which may have changed since it was written.

**Comment by russellbanks** [comment]
> Yes please, that will help.

I'll make the branch later today and update you :)

> I am unfamiliar with Compose for Desktop. Does it work with Kotlin/JVM? (Klogging only supports JVM right now.)

Compose for Desktop targets the JVM and is essentially just like any other Java application, for example, ones that use Java Swing or Java AWT. Therefore, there shouldn't be any issue with what platform the application targets.

**Comment by russellbanks** [comment]
Ah, thank you for finding this out. I thought it could be a conflict of dependencies. I'll downgrade to 0.3.2 and add Klogging :)

Is this something that would require migrating, I imagine, once Kotlin 1.7.0 is out?

**Comment by mjstrasser** [comment]
Yes, I will migrate Klogging to support Kotlin 1.7.

**Comment by mjstrasser** [comment]
@russellbanks I have updated Klogging to use Kotlin 1.7 and to not use the code that caused `IncompatibleClassChangeError` in HashHash. These changes are in the current `0.5.0-SNAPSHOT` version.

**Comment by russellbanks** [comment]
Hi, thank you for this. I'm actually currently using Klogging 0.4.6, which has fixed the issue for me and meant that I can go back to using Kotlinx-datetime 0.3.3 :)
