### ISSUE TITLE
Is LOGGERS threadsafe when running on JVM (LinkedHashMap)?

### ISSUE THREAD

**Issue by danny-su** [klogging/klogging#98]
Is LOGGERS threadsafe when running on JVM (LinkedHashMap)?

```kotlin
/**
 * Runtime list of current [Klogger] instances.
 */
private val LOGGERS: MutableMap<String, Klogger> = mutableMapOf()

/**
 * Returns a [Klogger] for the specified name: returning an existing one
 * or creating a new one if needed.
 */
internal fun loggerFor(name: String?): Klogger {
    // This property is lazily set by checking for a JSON configuration file.
    // TODO: Can we ensure this is not optimised out of the code?
    KloggingEngine.configuration
    val loggerName = name ?: "Klogger"
    return LOGGERS.getOrPut(loggerName) { KloggerImpl(loggerName) }
}

/** Returns a [Klogger] with the specified name. */
public fun logger(name: String): Klogger = loggerFor(name)

```

**Comment by mjstrasser** [comment]
Do you mean, is LOGGERS synchronized? (Threadsafe is a loaded term :-)

No it is not, as you can see from reading either Kotlin docs for [`getOrPut()` extension function](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/get-or-put.html) or Java docs for [`LinkedHashMap` class (Java 8)](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html).

Have you had problems with creation of loggers in Klogging? Or are you reading the code and expecting problems?

I believe the risk of problems is quite low. Loggers are only created early in the running of an application, so the map is only updated once per logger.

* If you [implement the `Klogging` interface](https://klogging.io/docs/loggers/defining-loggers#implement-klogging-interface), the map is only modified once, when the `logger` property of the class is used to log an event for the _first_ time.
* If you [define a logger directly](https://klogging.io/docs/loggers/defining-loggers#define-a-logger-directly), the map is only modified when the instance is constructed.
* If you [define a logger statically](https://klogging.io/docs/loggers/defining-loggers#static-reference), the map is only modified when the class is loaded.

**Comment by danny-su** [comment]
> Do you mean, is LOGGERS synchronized? (Threadsafe is a loaded term :-)
> 
> No it is not, as you can see from reading either Kotlin docs for [`getOrPut()` extension function](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/get-or-put.html) or Java docs for [`LinkedHashMap` class (Java 8)](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html).
> 
> Have you had problems with creation of loggers in Klogging? Or are you reading the code and expecting problems?
> 
> I believe the risk of problems is quite low. Loggers are only created early in the running of an application, so the map is only updated once per logger.
> 
> * If you [implement the `Klogging` interface](https://klogging.io/docs/loggers/defining-loggers#implement-klogging-interface), the map is only modified once, when the `logger` property of the class is used to log an event for the _first_ time.
> * If you [define a logger directly](https://klogging.io/docs/loggers/defining-loggers#define-a-logger-directly), the map is only modified when the instance is constructed.
> * If you [define a logger statically](https://klogging.io/docs/loggers/defining-loggers#static-reference), the map is only modified when the class is loaded.

I mean LinkedHashMap is not thread-safe. Concurrent invocations of logger function may cause the state of LOGGERS corrupted, lead to crash or endless loop.

**Comment by mjstrasser** [comment]
Yes, I understand what thread-safe means. It may only be an issue during map modification, which is rare and happens early in the life of an application, as I stated.

Have you had issues with concurrent modification of the LOGGERS map?

**Comment by mjstrasser** [comment]
Thanks @chancila and @danny-su for your interest in this. I have pushed a build that uses `ConcurrentHashMap` in the JVM.

Let me know what you think.
